### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Tim-Quattrochi** [Tim-Quattrochi/MERN-Starter#1]
I think this template can use a basic navbar. There is currently a logout button in the Dashboard.jsx and it is out of place because I was just testing it. Let's move it into a nav bar. Since this is a template, I haven't installed any CSS libraries and have just been creating a new folder for each Component/Page with the file inside with a .css file, and just writing regular minimum css.

For example:

```
src
└── components
    └── componentName
        ├── ComponentName.jsx
        ├── componentName.css
```

**How the log out works**

The logout is a function in the useAuthProvider hook called handleLogout.  I have created a `useAuthContext` hook that easily exports the `AuthContext` with `useContext(AuthContext)`.  So now, you can just import the `useAuthContext` from `hooks/useAuthContext` and have access to the returned functions. You can then destructure the function like so `const { handleLogout } = useAuthContext();`

Once clicked, this `handleLogout` function makes a post request to the `/auth/logout` endpoint which removes the cookie that contains the refresh token, deletes the user information from local storage, and dispatches type LOGOUT, which updates the state of the user.

This Navbar should have login, register, logout.

**User story** 

- As a logged in user, I do not want to see the login and register links
- As a logged in user I want to see the logout button on the navbar
- As a logged out user I should be able to see links in the navbar to login

**Comment by Mrbinmt** [comment]
working on it
