### ISSUE TITLE
Client Register Requirements

### ISSUE THREAD

**Issue by Tim-Quattrochi** [Tim-Quattrochi/MERN-Starter#2]
This template can use some register form validation. Currently I can sign up with a password with 1 character. Which is nice for testing the registration manually, but this is temporary.

**How the register works**

The register is a function in the useAuthProvider hook called register.  I have created a `useAuthContext` hook that easily exports the `AuthContext` with `useContext(AuthContext)`.  So now, you can just import the `useAuthContext` from `hooks/useAuthContext` and have access to the returned functions. You can then destructure the function like so `const { register } = useAuthContext();`

Once clicked, this `register` function makes a post request to the `/auth/register` endpoint , and dispatches type REGISTER, which updates the state of the user with the `users _id, name, email and accessToken`. Then it calls the `login` function to log them in with their newly created email and password.

Since the register logic is handled in the AuthProvider, we should set the form requirements there. Currently, any network errors are caught in the try/catch, so any checking of the password, name, email, confirmPassword from the userDetails inside this function would have to throw an Error with a message, for example 

```
if(!myCondition) { 
  throw Error("my custom error message")
}
```

Your error will now be sent to the catch, where the catch in the `handleSubmit` in the Register.jsx can display it to the user, prevent form submit, etc.

**User story** 

- As a user who wants to register I should be able to create a password with at least 7 characters
- As a user who wants to register, i don't want to accidentally create a password that is a typo
- As a user who wants to register, I shouldn't be able to submit any blank inputs

**Comment by pm-moyanor** [comment]
hey Tim, count me in! I'll help with this one 👍

**Comment by Tim-Quattrochi** [comment]
Thanks again, Paula! Very nice job!

**Comment by pm-moyanor** [comment]
Happy to help :)
